### ISSUE TITLE
Unnecessary Dependency on activerecord

### ISSUE THREAD

**Issue by klobuczek** [jsonapi-suite/jsonapi_suite#13]
Could the dependency on activerecord be moved to development_dependency? We are not using activerecord and including this gem unnecessarily causes its inclusion in our project.  People who use activerecord will include the gem explicitly anyway.

**Comment by richmolj** [comment]
@klobuczek Thanks for the heads up...this was actually caused by a legacy dependency I've now removed altogether. Use >= 0.6.3 and activerecord will not be a dependency. We do depend on Rails, but you can avoid this as well by only picking the libs you need from the suite. Please let me know if this works for you.

**Comment by klobuczek** [comment]
@richmolj if you add rails dependency this will automatically pull in activerecord. Isn't it possible for you to just specify the gems actually needed like: activesuport, activemodel, railtie etc.

**Comment by richmolj** [comment]
@klobuczek This might be more of a documentation issue. Some of the libraries in the Suite are not meant to be used outside of Rails, for instance [strong_resources](https://github.com/jsonapi-suite/strong_resources). So, if you are not using Rails and want to limit the dependencies you are pulling in:

```ruby
# Gemfile
gem 'jsonapi_compliable'
# gem 'jsonapi_errorable'
gem 'jsonapi_spec_helpers'
# gem 'strong_resources'

# app.rb
class TwitterApp < Sinatra::Application
  include JsonapiCompliable
end
```

The goal is for *basic* functionality to be independent of Rails (including activesupport, et al), but Rails is still a first-class citizen and some of the Suite's libraries will be purposefully coupled to it. I can see how documentation should be improved to make this more clear.

Does this make sense to you?

**Comment by klobuczek** [comment]
@richmolj we are using rails with neo4j (graph database). You could still treat Rails as first class citizen without any downsides by replacing this line in gemspec of jsonapi-suite:
```
spec.add_dependency 'rails', ['>= 4.1', '< 6']
```
with
```
spec.add_dependency 'activemodel', ['>= 4.1', '< 6']
spec.add_dependency 'actionpack', ['>= 4.1', '< 6'] #maybe even this line alone would suffice
spec.add_dependency 'railties', ['>= 4.1', '< 6']
```
and be much less prescriptive what users of your gem have to have included in their projects.
I know I could skip jsonapi-suite, but the ControllerMixin is helpful and would be nice not to have to rewrite or inline most of it.

**Comment by richmolj** [comment]
@klobuczek I understand what you are suggesting, I just don't know why it's helpful. If you're using Rails anyway, it seems this change would have no effect for you. If you are not using Rails, you'd probably prefer avoiding these dependencies altogether.

As depending simply on `rails` makes testing and maintenance easier, I'd like to avoid splitting out until I understand a clear benefit.

**Comment by klobuczek** [comment]
@richmolj I don't want to convince you to do something you are not comfortable with, but just for your understanding. With this gem suddenly our application has to install: actioncable, actionmailer, activejob, activerecord gems. This increases the application size in best case and some potential conflicts in worst case.
You could still keep rails as development_dependency without loosing any of the testing and maintenance benefits.
Believe me using a non standard ORM each time activerecord gem pops up in our Gemfile.lock I am having the same conversation with the gem author until the next gem does the same oversight.

Maybe an interesting read: http://www.mikeperham.com/2016/02/09/kill-your-dependencies/

**Comment by richmolj** [comment]
@klobuczek Its not that I don't want to make the change, it's that I don't understand the benefit.

> we are using rails

> suddenly our application has to install: actioncable, actionmailer, activejob, activerecord gems

If you are using Rails, didn't you already have to install those things...? Or you are saying, you use Rails but customized the default Gemfile and application.rb?

I'm a bit leery of depending on specific Rails sub-gems, since it's easy to enter a state where my tests no longer reflect real-world usage. Also, as the author of a collection of libraries that are pre-1.0, avoiding such specific targeting makes my life easier. That said, if you can shed some light on your specific scenario I'll gladly do what I can to help you out.

**Comment by klobuczek** [comment]
This is the top of out Gemfile:
```
  gem 'actionpack'
  gem 'activemodel'
  gem 'railties'
```
and this is the top of application.rb:
```
# Pick the frameworks you want:
require "active_model/railtie"
require "action_controller/railtie"
require "action_view/railtie"
require "sprockets/railtie"
require 'neo4j/railtie'
```

**Comment by richmolj** [comment]
@klobuczek thanks for the discussion. I've come around a bit on this - as long as we keep `activesupport`/`actionpack`/`railties` and don't try to narrow down further (for now) it makes sense. I should be able to get to it this weekend (strong_resource will need the same) or feel free to send a PR 🙂

**Comment by klobuczek** [comment]
@richmolj great. BTW it was great to meet you in Railsconf just at the right time to allow us to switch over from active_model_serializers. Thanks for the hint and your work.
BTW are you sure `activemodel` is not needed?

**Comment by richmolj** [comment]
You too @klobuczek! I'm super interested to see how the neo4j integration works out. If you end up writing an adapter would be cool to see and possibly to this project. Please don't hesitate to reach out directly if you have issues - richmolj@gmail.com

`activemodel` shouldn't be required, at least top of my head. The only relevant code is validation error handling, which is optional and doesn't strictly require `activemodel` (just the `#errors` interface)

**Comment by richmolj** [comment]
@klobuczek v0.6.5 now has only activesupport and actionpack as dependencies 👏

**Comment by klobuczek** [comment]
Great!
One more thing I noticed:
`jsonapi_spec_helpers` should probably be development dependency only in the gem and documented to be included in the `test` section of the application Gemfile. That's is pretty much the pattern nearly every gem follows. Otherwise all the rspec stuff will get into production.

**Comment by richmolj** [comment]
Agreed - feel free to PR or I can get to it this week.
