### ISSUE TITLE
Usage with non-persisted entities

### ISSUE THREAD

**Issue by aribouius** [jsonapi-suite/jsonapi_suite#20]
Does this library support rendering resources that are not backed by a database model?

For example, how would one go about creating an endpoint (in rails) that handled [exchanging access tokens](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension) (e.g. a short lived token for an extended one) for Facebooks OpenGraph API?

It looks like I can access the POST data via `deserialized_params.attributes` (bad idea?), but I am unsure how to render the results.  Creating a custom resource adapter seems like it might get me there, but also does not seems appropriate for this use case.

**Comment by richmolj** [comment]
> Does this library support rendering resources that are not backed by a database model?

Absolutely. Here's some pseudo code:

```ruby
# some unpersisted object
class Credentials
  attr_accessor :email, :password

  def initialize(attrs)
    attrs.each_pair { |k,v| send("#{k}=", v)
  end

    # this is the only code related to lack of persistence
  def id
    @id ||= SecureRandom.uuid
  end

  def token
    # your logic to mint the token
  end
end

# app/resources/credential_resource.rb
class CredentialResource < ApplicationResource
  type :credentials
  model Credential

  # require this in an initializer
  # we're setting a pass-through adapter bc we'll handle it ourselves
  use_adapter JsonapiCompliable::Adapters::Null

  # these attrs will be whitelisted from strong_resources
  def create(attrs)
    credentials = Credential.new(attrs)
    raise "nope!" unless credentials.valid?
    credentials
  end
end
```

Further reading:

* [How to use without activerecord](https://jsonapi-suite.github.io/jsonapi_suite/how-to-use-without-activerecord)
* [How to build an adapter](https://jsonapi-suite.github.io/jsonapi_suite/how-to-build-an-adapter)
* [JsonapiCompliable::Resource docs](https://jsonapi-suite.github.io/jsonapi_compliable/JsonapiCompliable/Resource.html)

Let me know if you have any trouble. Also feel free to email richmolj@gmail.com for a slack invite where you can get help for stuff like this.

**Comment by aribouius** [comment]
Fantastic, thanks @richmolj!
