### ISSUE TITLE
How to serialize STI ActiveRecord models

### ISSUE THREAD

**Issue by petrosp** [jsonapi-suite/jsonapi_suite#22]
Hey guys,

I have an ActiveRecord::Base `Order` model and two more inheriting from it using rails `STI` feature: `Complete < Order` and `Abandoned < Order`.

I have configured the `Order` model with the `Suite` and when I request the `OrdersController#index` method an error is raised:
```
ERROR: NameError: Undefined serializable class SerializableComplete
```
Does this mean that I need to create `Serializers` for each of the `Order#descendants`

Thanks!

**Comment by richmolj** [comment]
Hi @petrosp! That's what I do - one serializer per subclass. That way if I ever need to customize I have the right file structure already in place.

That said, you can write your own proc that looks up the serializable class. I know this is called an `inferrer` in [jsonapi-rb](http://jsonapi-rb.org/) but as that's a separate library I'm not sure the syntax off the top of my head. Maybe @beauby can chime in, or you could try the [jsonapi-rb gitter chatroom](https://gitter.im/jsonapi-rb).

**Comment by petrosp** [comment]
Guys, thanks for the advice, I am closing this.
