### ISSUE TITLE
JSONAPI Suite in an engine

### ISSUE THREAD

**Issue by petrosp** [jsonapi-suite/jsonapi_suite#30]
Hi guys,

Has anybody tested this gem as part of a Rails engine? The generators at least seem to not respect the engine's namespace, which is an unfortunate mishap.

Thanks, let me know please!

**Comment by richmolj** [comment]
Hey @petrosp - while I haven't used Suite in an engine myself, I can't think of a reason things wouldn't work. You could fix the generator [here in a PR if you'd like](https://github.com/jsonapi-suite/jsonapi_compliable/tree/master/lib/generators), but I think if you just manually fix the names everything should work.
