### ISSUE TITLE
How can I use some number type?

### ISSUE THREAD

**Issue by aguirrel** [jsonapi-suite/jsonapi_suite#36]
Hi guys,

I want to use some number type (double, float, decimal) but I always get:

```
ERROR: NoMethodError: undefined method `[]' for nil:NilClass
```

I just follow tutorial:

$ rails new blog --api -m https://raw.githubusercontent.com/jsonapi-suite/rails_template/master/all.rb
$ bundle exec rails generate model Invoice user:string price:float
$ bundle exec rake db:migrate
$ bundle exec rails g jsonapi:resource Invoice user:string price:float

boom! I get the error message on post.

Some idea?

Thanks a lot!

**Comment by richmolj** [comment]
Answered in Slack chat - and fixed! Thanks for raising it @aguirrel

**Comment by hector** [comment]
@richmolj could you post the solution here?
I had to create my own strong_param for floats

**Comment by richmolj** [comment]
If you upgrade to the latest compliable, you should no longer get an error. The swagger type is `:number` and the payload type is `Float`.

**Comment by hector** [comment]
How does this work?
I thought default declarations for strong_params where here:
https://github.com/jsonapi-suite/strong_resources/blob/master/lib/strong_resources/configuration.rb

**Comment by richmolj** [comment]
Yes - the mapping to `:number` is [here](https://github.com/jsonapi-suite/strong_resources/blob/master/lib/strong_resources/configuration.rb#L27) so `attribute :number`maps to `Parameters.decimal`. The payload bit is completely separate and is asserting on the rendered response as `Float` when running the generator.

**Comment by hector** [comment]
Thank you @richmolj 
Just in case my case helps someone: I had to use `ActionController::Parameters.float` because `ActionController::Parameters.decimal` was not accepting a Ruby's float, I guess it needs a BigDecimal. I do not remember if the error was happening at the controller level or when saving the Active Record model.

**Comment by richmolj** [comment]
Yes, there is an improvement needed here to support both float and decimal. I have this on my list, but happy to merge if youd like to take a crack at a PR
