### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kasperhelweg** [jsonapi-suite/jsonapi_suite#37]
Is there any particular reason that only specs are version name-spaced? For example,
 
    rails g jsonapi:resource User first_name:string last_name:string 

creates 

    spec/api/v1/users/...

but controllers, resources and serializers are created in directories

    /controllers/
    /resources/
    /serializers/

**Comment by richmolj** [comment]
Hey @kasperhelweg - I think this is correct; it really depends on how you want to deal with v2. For instance my company runs a separate fork on kubernetes and just routes to the right container based on `/v1` or `/v2`.

Similarly, you might want a new controller or serializer but not a new resource. The intent here is that the "default version" is v1, so there's no need to namespace.

**Comment by kasperhelweg** [comment]
That makes sense. Thanks!
