### ISSUE TITLE
Filtring with url params

### ISSUE THREAD

**Issue by A-Boudi** [jsonapi-suite/jsonapi_suite#44]
The JSON API specification states this:
> Note: JSON API is agnostic about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

Therefore, it is possible to filter results using the URL params like shown here: http://jsonapi.org/recommendations/#filtering

In #9, association filtering is used to filter the include part of the response. Is there a way to change this default behavior to filter the returned array instead of the include's content?

I know that I can use allow_filter with a block but I can't use the name of the relationship, I need to use another name.

Are you planning to implement this behavior? What are your thoughts about such behavior and where should I look to if I want to implement this?

**Comment by richmolj** [comment]
> I know that I can use allow_filter with a block but I can't use the name of the relationship, I need to use another name.

I think the best practice here is to be more explicit with the filter name. If we're hitting `/positions` you aren't filtering `department` - you're filtering `department_id` or `department_name`, etc.

That said, I believe [Graphiti](https://github.com/graphiti-api/graphiti) (the 1.0 version of Suite that is in alpha and will be beta shortly) would support either.

**Comment by A-Boudi** [comment]
The problem with allow_filter approach is that I need to repeat the same code in a lot of places. How can I DRY things up? Would we be able to migrate from current version to 1.0 version?

**Comment by richmolj** [comment]
I'm not sure what the repeated code would be?

Will be releasing a stable beta of Graphiti today, and yes I recommend upgrading if you can.

**Comment by A-Boudi** [comment]
We have a big number of resources and each resource have numerous relationships. Writing allow_filter for each relationships of each resource would be cumbersome and error prone.
The code would be roughly like this:
```
allow_filter :relationship do |scope, value|
  # Split value if it's and array
  scope.where([relationship_id = value])
end
```

I'll be glad to work on a PR (maybe in graphiti?), if this behavior is desired. Where should I look into?

**Comment by richmolj** [comment]
I'm not sure why you couldn't do `allow_filter :relationship_id`?

This is a first-class pattern in Graphiti:

```ruby
class PositionResource < ApplicationResource
  attribute :employee_id, :integer, only: [:filterable]
end
```

**Comment by A-Boudi** [comment]
I'm sorry, I didn't understand the first time that this behavior was already supported by using :relationship_id without defining the allow_filter block.

Thank you very much for your help.

**Comment by richmolj** [comment]
No worries, glad that works!
