### ISSUE TITLE
Resources do not inherit relationships

### ISSUE THREAD

**Issue by hector** [jsonapi-suite/jsonapi_suite#45]
I have found that if a `belongs_to` relationship is defined on a Parent resource, this relationship will not exist on a Child of the Parent.

Is it something to be fixed?

When defining attributes and relationships on serializers they get correctly inherited by children classes, and this is also the behaviour for Rails models.

For the time being, I will try to put the relationships of the parent in a module and include it on each children (or just use concerns).

**Comment by richmolj** [comment]
Fixed in Graphiti, the 1.0 version of Suite https://graphiti-api.github.io/graphiti/guides/

**Comment by hector** [comment]
Cool! I didn't know about that, should I upgrade from jsonapi-suite to Graphiti already? I mean, is it ready?

**Comment by richmolj** [comment]
It's in stable beta and should do an RC soon. I'd recommend it!
