### ISSUE TITLE
STI inheritance doubts

### ISSUE THREAD

**Issue by hector** [jsonapi-suite/jsonapi_suite#46]
I have not been able to find much documentation on how jsonapi_suite behaves when using Single Table Inheritance on a model. Would anybody be so kind to clarify some points? I'd be grateful.

Example scenario: a model `Pet` (parent class) can be of the kind `Cat` or `Dog` (children classes).

I have some doubts on what would be the recommended approach regarding controllers, resources, serializers and JSORM models. Is there a default way to do that?

Should I use a single `PetController` to manage all models? It seems like I can only define one resource kind (`jsonapi resource: DubbingResource`).

If I fetch index from `PetController` will JSORM instantiate the children models for Dog and Cat, or otherwise a generic Pet model?

What I have been doing for the moment is to define:
- `PetController`
- `CatController` and `DogController` which do NOT inherit from `PetController`
- `PetResource`
- `CatResource` and `DogResource` that inherit from `PetResource`
- `SerializablePet`
- `SerializableCat` and `SerializableDog` that inherit from `SerializablePet`
- JSORM model for `Pet`
- JSORM model for `Cat` and `Dog` that inherit from `Pet`

**Comment by richmolj** [comment]
Check out the Task Resource in Graphiti and let me know how it goes https://github.com/graphiti-api/employee_directory

**Comment by richmolj** [comment]
Also https://graphiti-api.github.io/graphiti/guides/concepts/resources#polymorphic-resources

**Comment by hector** [comment]
I see, thanks!
